
name: CI - Backend Endpoint Testing

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest python-dotenv

      - name: Load environment variables from .env
        run: |
          echo "Loading .env"
          cat .env >> $ENV_GITHUB

      - name: Run pytest
        run: |
          pytest backend/tests/test.py --maxfail=1 --disable-warnings -v
